[package]
name = "tutorial10_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "timer_future"
path = "src/lib.rs"

[dependencies]
futures = "0.3"